file(READ "${NDS_AICPU_MANIFEST}" manifest)
string(REGEX MATCHALL "\"opKernelLib\"[ \t]*:[ \t]*\"AICPUKernel\"" standard_entries "${manifest}")
list(LENGTH standard_entries standard_entry_count)
if(NOT standard_entry_count EQUAL 13)
    message(FATAL_ERROR "AICPU manifest must register all 13 entries as standard AICPUKernel operators")
endif()
if(NOT manifest MATCHES "nds_aicpu_storage_bootstrap_kernel")
    message(FATAL_ERROR "AICPU manifest must register the storage bootstrap operator")
endif()
if(manifest MATCHES "CUSTAICPUKernel")
    message(FATAL_ERROR "AICPU manifest must not move NDS operators into the isolated custom scheduler")
endif()
