if(TARGET nds_server_protocol)
    add_executable(nds_server main.cc)
    target_link_libraries(nds_server PRIVATE CLI11::CLI11 nds_logging nds_server_protocol)
    target_compile_options(nds_server PRIVATE -Wall -Wextra -Wpedantic -Werror)
    set_target_properties(nds_server PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
endif()
